class User:
    def __init__(self, username, password):
        self.username = username
        self.password = password

    def log_in(self):
        input('Enter username:\n')
        input('Enter password:\n')

    def display(self):
        print('username:\t', self.username)
        print('password:\t', self.password)

class Farmer(User):
    def __init__(self, username, password, farmID, location, cropdiseaseType):
        super().__init__(username, password)
        self.farmID = farmID
        self.location = location
        self.cropdiseaseType = cropdiseaseType

    def submitdata(self):
        input('Enter farm ID:\n')
        input('Enter location:\n')
        input('Enter crop disease Type:\n')
        User.log_in(self)

    def displaydata(self):
        print('Farm ID:\t', self.farmID)
        print('Location:\t', self.location)
        print('Crop disease Type:\t', self.cropdiseaseType)
        User.display(self)  

    #Report to be generated by researcher
    def viewreport(self):
        print('Awaiting report')


class Researcher(User):
    def __init__(self, username, password, researchID, expertise, affiliation):
        super().__init__(username, password)
        self.researchID = researchID
        self.expertise = expertise
        self.affiliation = affiliation

    def submitdata(self):
        input('Enter research Id:\t')
        input('Enter expertise level:\t')
        input('Enter affiliation')
        User.log_in(self)

    def displaydata(self):
        print('Research ID:\t', self.researchID)
        print('Expertise level:\t', self.expertise)
        print('Affiliation:\t', self.affiliation)
        User.display(self)

    #analyze crop disease type
    def analyzedata(self):
        print('Analysis of crop disease type')

    def generate_report(self):
        print('Here are the reports of the crop disease type')

class systemAdministrator(User):
    def __init__(self, username, password, adminID, accessLevel, permission):
        super().__init__(username, password)
        self.adminID = adminID
        self.accessLevel = accessLevel
        self.permission = permission

    def submitdata(self):
        input('Enter admin ID:\t')
        input('Enter access level:\t')
        input('Enter permission:\t')
        User.log_in(self)

    def displaydata(self):
        print('Admin ID:\t', self.adminID)
        print('Access level:\t', self.accessLevel)
        print('Permission granted?:\t', self.permission)
        User.display(self)

    def manage_users(self):
        print('Manage farmers and Researchers account')

    def train_models(self):
        print('Train machine learning models')                


